name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
          cd rust/main_logic
          cargo build --verbose
    - name: Run tests
      run: |
          cd rust/main_logic
          cargo test --verbose
