name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd rust/main_logic
          cargo build --verbose
      - name: Run tests
        run: |
          cd rust/main_logic
          cargo test --verbose
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Run tarpaulin
        run: |
          cd rust/main_logic
          cargo tarpaulin --out Xml --output-dir ../../
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./cobertura.xml
          flags: unittests
          verbose: true
